### ISSUE TITLE
error on line 3 at column 22: Opening and ending tag mismatch: CompanyIPPhoneDirectory line 0 and DirectoryEntry

### ISSUE THREAD

**Issue by jycemea** [sorvani/freepbx-helper-scripts#12]
Hi,

I got an error executing your code on http://192.XXX.XX.XXX/cm_to_yl_ab.php when CM is empty
I'm using FreeBPX 15 with and php7.3

![PHP_error_2020-11-07 103313](https://user-images.githubusercontent.com/19631789/98436641-b919af80-20e5-11eb-85a2-b12d9ff43816.jpg)
error on line 3 at column 22: Opening and ending tag mismatch: CompanyIPPhoneDirectory line 0 and DirectoryEntry

And when contacts are created in CM, I got a PDOException 
![PDO_exception_2020-11-07 115617](https://user-images.githubusercontent.com/19631789/98438107-7c06ea80-20f0-11eb-889c-ff53566d6188.jpg)

The png are attached. Can you help me to debug, please?

Thanks.

**Comment by sorvani** [comment]
Obviously, I never designed it to handle the empty state. I'll look into it.

**Comment by drcoccodrillus** [comment]
This part is fixed with my proposed patch. You can have a look here https://github.com/sorvani/freepbx-helper-scripts/pull/20
Now when the phone book is empty you get simply a neat and clean empty XML
![image](https://user-images.githubusercontent.com/35581959/213871853-70bed7ee-0017-46ee-b41e-8926f1c4f154.png)

**Comment by sorvani** [comment]
should be fixed by #20
